api_platform:
    title: StellarChain API
    version: 1.0.0
    defaults:
        stateless: true
        pagination_enabled: true
        pagination_items_per_page: 30
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
